version: "3.9"

services:
  stock-umi-dev:
    build:
      context: stock-umi
      dockerfile: docker/Dockerfile.dev
    image: stock-umi:dev
    container_name: stock-umi-dev
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-dev}
    networks:
      - backend
    ports:
      - 8001:80
    volumes:
      - ~/.ssh:/root/.ssh

  stock-go-dev:
    build:
      context: stock-go
      dockerfile: docker/Dockerfile.dev
    image: stock-go:dev
    container_name: stock-go-dev
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-dev}
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:-mongodb://mongo:27017}
      DB: ${DB:-stock}
      UC: ${UC:-http://user-center}
    volumes:
      - ~/.ssh:/root/.ssh
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    name: backend
    driver: bridge
